schema = 3

[mod]
  [mod."github.com/aws/aws-sdk-go"]
    version = "v1.40.45"
    hash = "sha256-7m4jOfXs356SUZG9tR+z3Yfa/O0CorkSkOXg/AmbqRM="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.0"
    hash = "sha256-zNSuzjr5n7zhK8VOciSigLMfbnHbmyzsWdTcMlV1kjQ="
  [mod."github.com/didip/tollbooth"]
    version = "v4.0.2+incompatible"
    hash = "sha256-M8K9oYioGBJnSH+Jrf16uwKbC0uacj6I2YiS1bD9W8o="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/jmespath/go-jmespath/internal/testify"]
    version = "v1.5.1"
    hash = "sha256-eOjXyGv7P1x+iO9rPrmAGvNj2JH5p36OgSiVyJv/hyI="
  [mod."github.com/joho/godotenv"]
    version = "v1.3.0"
    hash = "sha256-Vd43lAoKpbEeunlMySqf/TrfUckcxcHIk6YPdoGLKGY="
  [mod."github.com/patrickmn/go-cache"]
    version = "v2.1.0+incompatible"
    hash = "sha256-+i3/Cd9byb1q926jszLjadiUMUeux0VyGKnmP20EAoA="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/sashabaranov/go-openai"]
    version = "v1.14.0"
    hash = "sha256-9eNv8yTwCWxS8/NHpU8bzoTMiEDzbeIPPgKlKkKiM0s="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.0"
    hash = "sha256-az0Vd4MG3JXfaYbj0Q6AOmNkrXgmXDeQm8+BBiDXmdA="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20210614182718-04defd469f4e"
    hash = "sha256-Vr8T9YQsGq47z29sPSdI5Cd+DyRHxF6JnDsJDntnrW0="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20210423082822-04245dca01da"
    hash = "sha256-RmbxPPNSEJ71cgwQWXJUh7ZhqGWudgbs/pstc8Z9gHA="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20201126162022-7de9c90e9dd1"
    hash = "sha256-ykpqi1F7Yzo1BVwuG0nbQOZnK0qevcCD2xqbXbsoQq0="
  [mod."golang.org/x/text"]
    version = "v0.3.6"
    hash = "sha256-yP/VW8PvNE6ub82oSu0mnG3VZXMo1PCSbwsWbciQDaw="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20210723032227-1f47c861a9ac"
    hash = "sha256-YygVh3tohBFn6Or1txGRgeaCaCoMJLhEmKaKxLkjLbc="
  [mod."golang.org/x/tools"]
    version = "v0.0.0-20180917221912-90fa682c2a6e"
    hash = "sha256-NPoE7uVvwjV2PRIxI3DpegOZc8IuUs4XUJuH3ubKHJg="
  [mod."gopkg.in/check.v1"]
    version = "v0.0.0-20161208181325-20d25e280405"
    hash = "sha256-1w5mgYaZUC52uzDnpXXVqle/9AVkH4WePSrQFOVANUw="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.2.8"
    hash = "sha256-/KoaoUbFCm3r8nZyPaWZshMVTM2iSebS5kz/5rc+zsY="
