// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/pastebin.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Paste messages
type CreatePasteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePasteRequest) Reset() {
	*x = CreatePasteRequest{}
	mi := &file_proto_pastebin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePasteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePasteRequest) ProtoMessage() {}

func (x *CreatePasteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pastebin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePasteRequest.ProtoReflect.Descriptor instead.
func (*CreatePasteRequest) Descriptor() ([]byte, []int) {
	return file_proto_pastebin_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePasteRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreatePasteRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type CreatePasteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePasteResponse) Reset() {
	*x = CreatePasteResponse{}
	mi := &file_proto_pastebin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePasteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePasteResponse) ProtoMessage() {}

func (x *CreatePasteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pastebin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePasteResponse.ProtoReflect.Descriptor instead.
func (*CreatePasteResponse) Descriptor() ([]byte, []int) {
	return file_proto_pastebin_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePasteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPasteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPasteRequest) Reset() {
	*x = GetPasteRequest{}
	mi := &file_proto_pastebin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPasteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPasteRequest) ProtoMessage() {}

func (x *GetPasteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pastebin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPasteRequest.ProtoReflect.Descriptor instead.
func (*GetPasteRequest) Descriptor() ([]byte, []int) {
	return file_proto_pastebin_proto_rawDescGZIP(), []int{2}
}

func (x *GetPasteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPasteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPasteResponse) Reset() {
	*x = GetPasteResponse{}
	mi := &file_proto_pastebin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPasteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPasteResponse) ProtoMessage() {}

func (x *GetPasteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pastebin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPasteResponse.ProtoReflect.Descriptor instead.
func (*GetPasteResponse) Descriptor() ([]byte, []int) {
	return file_proto_pastebin_proto_rawDescGZIP(), []int{3}
}

func (x *GetPasteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPasteResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GetPasteResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetPasteResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// Diff messages
type CreateDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Original      string                 `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	Modified      string                 `protobuf:"bytes,2,opt,name=modified,proto3" json:"modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDiffRequest) Reset() {
	*x = CreateDiffRequest{}
	mi := &file_proto_pastebin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiffRequest) ProtoMessage() {}

func (x *CreateDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pastebin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiffRequest.ProtoReflect.Descriptor instead.
func (*CreateDiffRequest) Descriptor() ([]byte, []int) {
	return file_proto_pastebin_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDiffRequest) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *CreateDiffRequest) GetModified() string {
	if x != nil {
		return x.Modified
	}
	return ""
}

type CreateDiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDiffResponse) Reset() {
	*x = CreateDiffResponse{}
	mi := &file_proto_pastebin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiffResponse) ProtoMessage() {}

func (x *CreateDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pastebin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiffResponse.ProtoReflect.Descriptor instead.
func (*CreateDiffResponse) Descriptor() ([]byte, []int) {
	return file_proto_pastebin_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDiffResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiffRequest) Reset() {
	*x = GetDiffRequest{}
	mi := &file_proto_pastebin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiffRequest) ProtoMessage() {}

func (x *GetDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pastebin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiffRequest.ProtoReflect.Descriptor instead.
func (*GetDiffRequest) Descriptor() ([]byte, []int) {
	return file_proto_pastebin_proto_rawDescGZIP(), []int{6}
}

func (x *GetDiffRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OldText       string                 `protobuf:"bytes,2,opt,name=old_text,json=oldText,proto3" json:"old_text,omitempty"`
	NewText       string                 `protobuf:"bytes,3,opt,name=new_text,json=newText,proto3" json:"new_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiffResponse) Reset() {
	*x = GetDiffResponse{}
	mi := &file_proto_pastebin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiffResponse) ProtoMessage() {}

func (x *GetDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pastebin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiffResponse.ProtoReflect.Descriptor instead.
func (*GetDiffResponse) Descriptor() ([]byte, []int) {
	return file_proto_pastebin_proto_rawDescGZIP(), []int{7}
}

func (x *GetDiffResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDiffResponse) GetOldText() string {
	if x != nil {
		return x.OldText
	}
	return ""
}

func (x *GetDiffResponse) GetNewText() string {
	if x != nil {
		return x.NewText
	}
	return ""
}

// Completion messages
type GetCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletionRequest) Reset() {
	*x = GetCompletionRequest{}
	mi := &file_proto_pastebin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletionRequest) ProtoMessage() {}

func (x *GetCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pastebin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletionRequest.ProtoReflect.Descriptor instead.
func (*GetCompletionRequest) Descriptor() ([]byte, []int) {
	return file_proto_pastebin_proto_rawDescGZIP(), []int{8}
}

func (x *GetCompletionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completions   []string               `protobuf:"bytes,1,rep,name=completions,proto3" json:"completions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletionResponse) Reset() {
	*x = GetCompletionResponse{}
	mi := &file_proto_pastebin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletionResponse) ProtoMessage() {}

func (x *GetCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pastebin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletionResponse.ProtoReflect.Descriptor instead.
func (*GetCompletionResponse) Descriptor() ([]byte, []int) {
	return file_proto_pastebin_proto_rawDescGZIP(), []int{9}
}

func (x *GetCompletionResponse) GetCompletions() []string {
	if x != nil {
		return x.Completions
	}
	return nil
}

var File_proto_pastebin_proto protoreflect.FileDescriptor

const file_proto_pastebin_proto_rawDesc = "" +
	"\n" +
	"\x14proto/pastebin.proto\x12\bpastebin\"D\n" +
	"\x12CreatePasteRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"%\n" +
	"\x13CreatePasteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fGetPasteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"h\n" +
	"\x10GetPasteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"K\n" +
	"\x11CreateDiffRequest\x12\x1a\n" +
	"\boriginal\x18\x01 \x01(\tR\boriginal\x12\x1a\n" +
	"\bmodified\x18\x02 \x01(\tR\bmodified\"$\n" +
	"\x12CreateDiffResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eGetDiffRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x0fGetDiffResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bold_text\x18\x02 \x01(\tR\aoldText\x12\x19\n" +
	"\bnew_text\x18\x03 \x01(\tR\anewText\"*\n" +
	"\x14GetCompletionRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"9\n" +
	"\x15GetCompletionResponse\x12 \n" +
	"\vcompletions\x18\x01 \x03(\tR\vcompletions2\xfb\x02\n" +
	"\x0fPastebinService\x12J\n" +
	"\vCreatePaste\x12\x1c.pastebin.CreatePasteRequest\x1a\x1d.pastebin.CreatePasteResponse\x12A\n" +
	"\bGetPaste\x12\x19.pastebin.GetPasteRequest\x1a\x1a.pastebin.GetPasteResponse\x12G\n" +
	"\n" +
	"CreateDiff\x12\x1b.pastebin.CreateDiffRequest\x1a\x1c.pastebin.CreateDiffResponse\x12>\n" +
	"\aGetDiff\x12\x18.pastebin.GetDiffRequest\x1a\x19.pastebin.GetDiffResponse\x12P\n" +
	"\rGetCompletion\x12\x1e.pastebin.GetCompletionRequest\x1a\x1f.pastebin.GetCompletionResponseB\x1dZ\x1bgithub.com/pastebin/api;apib\x06proto3"

var (
	file_proto_pastebin_proto_rawDescOnce sync.Once
	file_proto_pastebin_proto_rawDescData []byte
)

func file_proto_pastebin_proto_rawDescGZIP() []byte {
	file_proto_pastebin_proto_rawDescOnce.Do(func() {
		file_proto_pastebin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pastebin_proto_rawDesc), len(file_proto_pastebin_proto_rawDesc)))
	})
	return file_proto_pastebin_proto_rawDescData
}

var file_proto_pastebin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_pastebin_proto_goTypes = []any{
	(*CreatePasteRequest)(nil),    // 0: pastebin.CreatePasteRequest
	(*CreatePasteResponse)(nil),   // 1: pastebin.CreatePasteResponse
	(*GetPasteRequest)(nil),       // 2: pastebin.GetPasteRequest
	(*GetPasteResponse)(nil),      // 3: pastebin.GetPasteResponse
	(*CreateDiffRequest)(nil),     // 4: pastebin.CreateDiffRequest
	(*CreateDiffResponse)(nil),    // 5: pastebin.CreateDiffResponse
	(*GetDiffRequest)(nil),        // 6: pastebin.GetDiffRequest
	(*GetDiffResponse)(nil),       // 7: pastebin.GetDiffResponse
	(*GetCompletionRequest)(nil),  // 8: pastebin.GetCompletionRequest
	(*GetCompletionResponse)(nil), // 9: pastebin.GetCompletionResponse
}
var file_proto_pastebin_proto_depIdxs = []int32{
	0, // 0: pastebin.PastebinService.CreatePaste:input_type -> pastebin.CreatePasteRequest
	2, // 1: pastebin.PastebinService.GetPaste:input_type -> pastebin.GetPasteRequest
	4, // 2: pastebin.PastebinService.CreateDiff:input_type -> pastebin.CreateDiffRequest
	6, // 3: pastebin.PastebinService.GetDiff:input_type -> pastebin.GetDiffRequest
	8, // 4: pastebin.PastebinService.GetCompletion:input_type -> pastebin.GetCompletionRequest
	1, // 5: pastebin.PastebinService.CreatePaste:output_type -> pastebin.CreatePasteResponse
	3, // 6: pastebin.PastebinService.GetPaste:output_type -> pastebin.GetPasteResponse
	5, // 7: pastebin.PastebinService.CreateDiff:output_type -> pastebin.CreateDiffResponse
	7, // 8: pastebin.PastebinService.GetDiff:output_type -> pastebin.GetDiffResponse
	9, // 9: pastebin.PastebinService.GetCompletion:output_type -> pastebin.GetCompletionResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pastebin_proto_init() }
func file_proto_pastebin_proto_init() {
	if File_proto_pastebin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pastebin_proto_rawDesc), len(file_proto_pastebin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pastebin_proto_goTypes,
		DependencyIndexes: file_proto_pastebin_proto_depIdxs,
		MessageInfos:      file_proto_pastebin_proto_msgTypes,
	}.Build()
	File_proto_pastebin_proto = out.File
	file_proto_pastebin_proto_goTypes = nil
	file_proto_pastebin_proto_depIdxs = nil
}
